name: CD

on:
  push:
  push:
    branches:
      - main
      - master
      - cicd/create-cd-workflow
    # Trigger on version tags for production deployments
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0, v2.1.3, etc.

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  DEPLOYMENT_ROLE: ${{ vars.DEPLOYMENT_ROLE_NAME }}

jobs:
  cd:
    # Set environment based on whether the ref is a tag or a branch
    # If it's a tag starting with 'v', use 'production', else 'development'
    environment:  ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'development' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v5

    - name: Display Deployment Context
      run: |
        echo "::group::Deployment Context"
        echo "Deploying to environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'development' }}"
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub Event: ${{ github.event_name }}"
        echo "AWS Region: ${{ env.AWS_REGION }}"
        echo "AWS Account ID: ********${{ env.AWS_ACCOUNT_ID }}" | sed -E 's/.*([0-9]{4})$/AWS Account ID: ********\1/'
        echo "Deployment Role: ${{ env.DEPLOYMENT_ROLE }}"
        echo "::endgroup::"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.DEPLOYMENT_ROLE }}
        role-session-name: DeploymentSession
    - name: Test AWS Credentials
      run: aws sts get-caller-identity
    - name: List S3 Bucket contents
      run: aws s3 ls s3://demir-tic-tac-toe
