name: CD

on:
  pull_request:
    branches:
      - main
      - master
  
  # For testing only. TODO: remove before merging to main/master
  push:
    branches:
      - cicd/create-cd-workflow

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 259130455157
  DEPLOYMENT_ROLE: github-actions-role

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v5
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.DEPLOYMENT_ROLE }}
        role-session-name: DeploymentSession
    - name: Test AWS Credentials
      run: aws sts get-caller-identity
    - name: List S3 Bucket contents
      run: aws s3 ls s3://demir-tic-tac-toe
