name: Build and Publish Docker Image

on:
  push:
    branches: 
      - main
      - master
      - cicd/iac-setup

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare Environment Variables
        run: |
          # Downcase the repository name and set it as an environment variable
          echo "repository_name=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Display Execution Context
        run: |
          echo "::group::Execution Context"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Username for Container Registry login : ${{ github.repository_owner }}"
          echo "Repository Name (raw): ${{ github.repository }}"
          echo "Repository Name (lowercased): ${{ env.repository_name }}"
          echo "::endgroup::"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infra/services/queues/batch-etl/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.repository_name }}/arkad-rabbitmq-batch:latest
            ghcr.io/${{ env.repository_name }}/arkad-rabbitmq-batch:${{ github.sha }}
